### ISSUE TITLE
TypeError: ('Could not adapt', Process('sample'), <InterfaceClass shoobx.wfmc.interfaces.IPythonExpressionEvaluator>)

### ISSUE THREAD

**Issue by zopyx** [Shoobx/shoobx.wfmc#4]
```
persistent==4.2.4.2
shoobx.wfmc==4.1.1
zope.cachedescriptors==4.3.1
zope.component==4.4.1
zope.event==4.3.0
zope.interface==4.5.0
```

```

from shoobx.wfmc import process

pd = process.ProcessDefinition('sample')

pd.defineActivities(
    author  = process.ActivityDefinition(),
    review  = process.ActivityDefinition(),
    publish = process.ActivityDefinition(),
    reject  = process.ActivityDefinition(),
)


pd.defineTransitions(
    process.TransitionDefinition('author', 'review'),
    process.TransitionDefinition('review', 'publish'),
    process.TransitionDefinition('review', 'reject'),
)

import zope.component
from shoobx.wfmc.process import StaticProcessDefinitionFactory
pdfactory = StaticProcessDefinitionFactory()
zope.component.provideUtility(pdfactory)
pdfactory.register(pd)


def log_workflow(event):
    print (event)
import zope.event
zope.event.subscribers.append(log_workflow)


proc = pd()

proc.start()
```

```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    proc.start()
  File "/Users/ajung/src/shoobx.wfmc/lib/python3.6/site-packages/shoobx/wfmc/process.py", line 666, in start
    evaluator = interfaces.IPythonExpressionEvaluator(self)
TypeError: ('Could not adapt', Process('sample'), <InterfaceClass shoobx.wfmc.interfaces.IPythonExpressionEvaluator>)

```

**Comment by agroszer** [comment]
oops you need to register
```
<adapter 
    for="shoobx.wfmc.interfaces.IProcess"
    factory="shoobx.wfmc.process.PythonExpressionEvaluator" />
```

don't know why the repo is missing zcml

**Comment by zopyx** [comment]
Also missing the release...I wonder why the tests pass with `tox`

**Comment by agroszer** [comment]
what do you mean with "Also missing the release" ?

**Comment by zopyx** [comment]
I installed the package first from PyPI and received the error above. Then I rechecked with a fresh checkout.
